#!/bin/bash
log='/var/log/noip.log'
datadir='/var/lib/noip'
if [ -f /etc/mininoip.conf ]; then
. /etc/mininoip.conf
else
	echo "$(date '+%F %T') Missing configure file: /etc/mininoip.conf" >> $log
	echo "See sample configure in /usr/share/doc/mininoip/mininoip.conf"
	exit -1
fi

if [[ ! -d "$datadir" ]]; then
  	mkdir $datadir
fi

if [ "$#" = "2" -a "$1" = "wait" ]; then
	# Wait 30s for internet available
	sleep 30
fi



ipfile=$datadir/noip

if [ ! -f $datadir/noip ]; then
	echo "192.168.1.1" > $ipfile
fi

myip=$(wget -q -O- http://ip1.dynupdate.no-ip.com) || { echo "$(date '+%F %T') Can't get your ip" >> $log; exit -1; }
# Check ip is chaged or not
if [ "$myip" = "$(cat $ipfile)" ]; then
	exit 0
fi

echo $myip > $ipfile
tmp=$(tempfile)

# Send request to server:
if wget -q -O $tmp --http-user=$username --http-password=$pass \
	https://dynupdate.no-ip.com/nic/update?hostname=$hostlist;
then
	echo "$(date '+%F %T') h[]=$hostlist: ip=$myip" >> $log

# Check Status, first word in response indicate status, the second normally is IP
	read -a resp < $tmp
	case "${resp[0]}" in
		good)
			echo "Success: DNS hostname update successful."
        ;;
		nochg)
			echo "Success: IP address is current, no update performed. Followed by a space and the IP address that it is currently set to."
        ;;
		nohost)
			echo "Error: Hostname supplied does not exist under specified account, client exit and require user to enter new login credentials before performing and additional request."
        ;;
		badauth)
			echo "Error: Invalid username password combination"
        ;;
		badagent)
			echo "Error: Client disabled. Client should exit and not perform any more updates without user intervention."
        ;;
		\!nonator)
         echo "An update request was sent including a feature that is not available to that particular user such as offline options."
		;;
		abuse)
			echo "Error: Username is blocked due to abuse. Either for not following our update specifications or disabled due to violation of the No-IP terms of service. Our terms of service can be viewed at http://www.noip.com/legal/tos. Client should stop sending updates."
        ;;
		911)
			echo "Error: A fatal error on our side such as a database outage. Retry the update no sooner 30 minutes."
        ;;
		*)
			echo "Invalid response: $resp"
		;;

	esac
fi
# Remove temp file if it exit.
if [ -f $tmp ]; then
	rm $tmp
fi
exit 0
