.TH NOIP "1" "October 2013" "noip 2.2.4" "User Commands"
.SH NAME
noip \- manual page for noip 2.2.4
.SH SYNOPSIS
Usage: noip [ \fB\-C\fR [ \fB\-F][\fR \fB\-Y][\fR \fB\-U\fR #min]
[ \fB\-u\fR username][ \fB\-p\fR password][ \fB\-x\fR progname]]
[ \fB\-c\fR file][ \fB\-i\fR addr][ \fB\-S][\fR \fB\-M][\fR \fB\-h]\fR
.SH DESCRIPTION
.PP
no-ip.com dynamic IP update client for Linux
.SH OPTIONS
.TP
\fB\-C\fR
create configuration data
.TP
\fB\-F\fR
force NAT off
.TP
\fB\-Y\fR
select all hosts/groups
.TP
\fB\-U\fR minutes
set update interval
.TP
\fB\-u\fR username
use supplied username
.TP
\fB\-p\fR password
use supplied password
.TP
\fB\-x\fR executable
use supplied executable
.TP
\fB\-c\fR config_file
use alternate data path
.TP
\fB\-i\fR IPaddress
use supplied address
.TP
\fB\-I\fR interface
use supplied interface
.TP
\fB\-S\fR
show configuration data
.TP
\fB\-M\fR
permit multiple instances
.TP
\fB\-K\fR processID
terminate instance PID
.TP
\fB\-z\fR
activate shm dump code
.TP
\fB\-h\fR
help
.SH VERSIONS
.B noip
for
.B Linux
version 2.2.4rc1
.SH BUGS
.PP
Report bug to <bugs@no\-ip.com>
.SH "SEE ALSO"
.B noip
homepage: <http://www.no\-ip.com>.
.PP
Copyright (C) 2000-2013 Free Software Foundation, Inc.
